version: '3.9'

services:
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    hostname: node_exporter
    container_name: node_exporter
    networks:
      - monitoring
    pid: host
    volumes:
      - "/:/host:ro,rslave"
    command:
      - --path.rootfs=/host

  grafana:
    image: grafana/grafana:latest
    hostname: grafana
    container_name: grafana
    networks:
      - monitoring
    depends_on:
      - prometheus
    ports:
      - "3000:3000" # Expose port 3000 on the host

  podman_exporter:
    image: quay.io/navidys/prometheus-podman-exporter
    hostname: podman_exporter
    container_name: podman_exporter
    environment:
      - CONTAINER_HOST=unix:///run/podman/podman.sock
    volumes:
      - /run/user/1000/podman/podman.sock:/run/podman/podman.sock:ro
    networks:
      - monitoring  # ports: - 9882:9882
    command:
      - /bin/podman-exporter
      - --collector.enable-all

  prometheus:
    image: docker.io/prom/prometheus
    hostname: prometheus
    container_name: prometheus
    networks:
      - monitoring
    depends_on:
      - podman_exporter
      - node_exporter
    volumes:
      - ./prometheus:/etc/prometheus

networks:
  monitoring:
    external: false
